apiVersion: v1
kind: Service
metadata:
  name: podinfo
spec:
  type: LoadBalancer
  selector:
    app: podinfo
  ports:
    - name: http
      port: http
      protocol: TCP
      targetPort: 9898
    - name: grpc
    - port: grpc
      protocol: TCP
      targetPort: 9999