apiVersion: v1
kind: Service
metadata:
  name: podinfo
spec:
  type: LoadBalancer
  selector:
    app: podinfo
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 9898
    - name: grpc
      port: 8080
      protocol: TCP
      targetPort: 9999
